export const COMANDOS_SCHEMA = [
  "CREATE CONSTRAINT candidatura_sq IF NOT EXISTS FOR (c:Candidatura) REQUIRE c.sq IS UNIQUE",
  "CREATE CONSTRAINT pessoa_chave IF NOT EXISTS FOR (p:Pessoa) REQUIRE p.chave IS UNIQUE",
  "CREATE CONSTRAINT organizacao_cnpj IF NOT EXISTS FOR (o:Organizacao) REQUIRE o.cnpj IS UNIQUE",
  "CREATE CONSTRAINT partido_numero IF NOT EXISTS FOR (p:Partido) REQUIRE p.numero IS UNIQUE",
  "CREATE CONSTRAINT uf_sigla IF NOT EXISTS FOR (u:Uf) REQUIRE u.sigla IS UNIQUE",
  "CREATE CONSTRAINT cargo_codigo IF NOT EXISTS FOR (c:Cargo) REQUIRE c.codigo IS UNIQUE",
  "CREATE CONSTRAINT eleicao_id IF NOT EXISTS FOR (e:Eleicao) REQUIRE e.id IS UNIQUE",
  "CREATE CONSTRAINT federacao_numero IF NOT EXISTS FOR (f:Federacao) REQUIRE f.numero IS UNIQUE",
  "CREATE CONSTRAINT coligacao_id IF NOT EXISTS FOR (c:Coligacao) REQUIRE c.id IS UNIQUE",
  "CREATE CONSTRAINT despesa_id IF NOT EXISTS FOR (d:Despesa) REQUIRE d.id IS UNIQUE",
  "CREATE CONSTRAINT pagamento_id IF NOT EXISTS FOR (p:Pagamento) REQUIRE p.id IS UNIQUE",
  "CREATE CONSTRAINT receita_id IF NOT EXISTS FOR (r:Receita) REQUIRE r.id IS UNIQUE",
  "CREATE CONSTRAINT bem_id IF NOT EXISTS FOR (b:Bem) REQUIRE b.id IS UNIQUE",
  "CREATE CONSTRAINT rede_url IF NOT EXISTS FOR (r:RedeSocial) REQUIRE r.url IS UNIQUE",
  "CREATE CONSTRAINT historico_id IF NOT EXISTS FOR (h:CandidaturaAnterior) REQUIRE h.id IS UNIQUE",
  "CREATE CONSTRAINT motivo_id IF NOT EXISTS FOR (m:Motivo) REQUIRE m.id IS UNIQUE",
  "CREATE CONSTRAINT processo_numero IF NOT EXISTS FOR (p:Processo) REQUIRE p.numero IS UNIQUE",
  "CREATE CONSTRAINT vaga_id IF NOT EXISTS FOR (v:Vaga) REQUIRE v.id IS UNIQUE",
  "CREATE CONSTRAINT conta_cnpj IF NOT EXISTS FOR (c:ContaCampanha) REQUIRE c.cnpj IS UNIQUE",
  "CREATE CONSTRAINT orgao_id IF NOT EXISTS FOR (o:OrgaoPartidario) REQUIRE o.id IS UNIQUE",
  "CREATE CONSTRAINT agente_id IF NOT EXISTS FOR (a:AgenteNaoIdentificado) REQUIRE a.id IS UNIQUE",
  "CREATE CONSTRAINT comprovante_url IF NOT EXISTS FOR (c:Comprovante) REQUIRE c.url IS UNIQUE",
  "CREATE INDEX candidatura_uf IF NOT EXISTS FOR (c:Candidatura) ON (c.uf)",
  "CREATE INDEX candidatura_nome IF NOT EXISTS FOR (c:Candidatura) ON (c.nomeBusca)",
  "CREATE INDEX despesa_sq IF NOT EXISTS FOR (d:Despesa) ON (d.sqTse)",
  "CREATE INDEX despesa_grupo IF NOT EXISTS FOR (d:Despesa) ON (d.grupo)",
  "CREATE INDEX receita_sq IF NOT EXISTS FOR (r:Receita) ON (r.sqTse)",
  "CREATE CONSTRAINT empresa_basico IF NOT EXISTS FOR (e:Empresa) REQUIRE e.cnpjBasico IS UNIQUE",
  "CREATE CONSTRAINT cnae_codigo IF NOT EXISTS FOR (c:Cnae) REQUIRE c.codigo IS UNIQUE",
  "CREATE CONSTRAINT natureza_codigo IF NOT EXISTS FOR (n:NaturezaJuridica) REQUIRE n.codigo IS UNIQUE",
  "CREATE CONSTRAINT qualificacao_codigo IF NOT EXISTS FOR (q:Qualificacao) REQUIRE q.codigo IS UNIQUE",
  "CREATE CONSTRAINT municipio_receita IF NOT EXISTS FOR (m:Municipio) REQUIRE m.codigo IS UNIQUE",
  "CREATE CONSTRAINT motivo_situacao IF NOT EXISTS FOR (m:MotivoSituacao) REQUIRE m.codigo IS UNIQUE",
];
